// Generates src/generated/protocolConstants.ts: the protocol numbers, the capability strings and the
// permission-mode strings, from crates/claude-runtime-protocol/capabilities.json -- the one source
// both this sidecar and the Rust crate (its build.rs emits `pub const`s from the same file) read.
//
// Generated rather than read at runtime, for the reason scripts/generateSdkVersions.mjs is: a packaged
// single-file build has no filesystem beside it, so a JSON file opened at startup would build clean and
// die on its first run. Generating leaves the runtime with literals; tests/protocolSource.test.ts
// re-reads the file and fails if the generated copy ever disagrees with it.
//
// The file is refused, not interpreted, when it is malformed -- the same checks build.rs makes, so a
// mistake stops both sides at build time: a duplicate or invalid name, `baseline` on anything but
// minor 0, an `executable_*` capability that is not last (the wire order is part of the contract),
// a `when` this sidecar does not know, a ledger that does not list every minor up to the current one.

import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const workspaceRoot = join(here, '..');
const sourcePath = join(workspaceRoot, '..', '..', 'crates', 'claude-runtime-protocol', 'capabilities.json');

/** The conditions a capability may carry in `when`: facts of THIS process or build that decide
 * whether it is advertised. Each is wired in src/capabilities.ts. */
const KNOWN_CONDITIONS = ['egress_restricted', 'sdk_bundled'];
const NAME = /^[a-z][a-z0-9_]*$/;

const fail = (message) => {
  throw new Error(`generateProtocolConstants: ${sourcePath}: ${message}`);
};

let doc;
try {
  doc = JSON.parse(readFileSync(sourcePath, 'utf8'));
} catch (error) {
  fail(`cannot read or parse it: ${error.message}`);
}

const { major, minor } = doc.protocol ?? {};
if (!Number.isInteger(major) || major < 1 || !Number.isInteger(minor) || minor < 0) {
  fail(`protocol must carry an integer major >= 1 and minor >= 0, got ${JSON.stringify(doc.protocol)}`);
}
const ledger = (doc.minors ?? []).map((entry) => entry.minor);
if (JSON.stringify(ledger) !== JSON.stringify(Array.from({ length: minor + 1 }, (_, i) => i))) {
  fail(`minors must list 0..${minor} in order, got ${JSON.stringify(ledger)}`);
}

const seen = new Set();
const capabilities = [];
for (const entry of doc.capabilities ?? []) {
  const { name, since_minor: sinceMinor, baseline = false, when } = entry;
  if (typeof name !== 'string' || !NAME.test(name) || seen.has(name)) {
    fail(`capability ${JSON.stringify(name)} is not a unique lower_snake_case name`);
  }
  seen.add(name);
  if (!Number.isInteger(sinceMinor) || sinceMinor < 0 || sinceMinor > minor) {
    fail(`${name}: since_minor ${JSON.stringify(sinceMinor)} is not an integer in 0..${minor}`);
  }
  if (typeof baseline !== 'boolean' || (baseline && sinceMinor !== 0)) {
    fail(`${name}: baseline must be a boolean, and only minor 0 can be baseline -- the baseline is what major ${major} itself guarantees`);
  }
  if (when !== undefined && !KNOWN_CONDITIONS.includes(when)) {
    fail(`${name}: unknown condition ${JSON.stringify(when)} (known: ${KNOWN_CONDITIONS.join(', ')})`);
  }
  capabilities.push({ name, sinceMinor, baseline, when });
}
const firstExecutable = capabilities.findIndex((c) => c.name.startsWith('executable_'));
if (firstExecutable >= 0 && !capabilities.slice(firstExecutable).every((c) => c.name.startsWith('executable_'))) {
  fail('the executable_* capabilities must stay last');
}

const permissionModes = doc.permission_modes ?? [];
if (!Array.isArray(permissionModes) || permissionModes.length === 0 || !permissionModes.every((m) => typeof m === 'string' && NAME.test(m)) || new Set(permissionModes).size !== permissionModes.length) {
  fail(`permission_modes must be a non-empty list of unique lower_snake_case names, got ${JSON.stringify(permissionModes)}`);
}

const literal = (value) => JSON.stringify(value);
const out = join(workspaceRoot, 'src', 'generated', 'protocolConstants.ts');
mkdirSync(dirname(out), { recursive: true });
writeFileSync(
  out,
  `// GENERATED by scripts/generateProtocolConstants.mjs from crates/claude-runtime-protocol/capabilities.json --
// do not edit, and do not commit (src/generated/ is ignored). Regenerated by \`npm run generate\`, which
// \`npm run build\` runs first. Drift from the file is caught by tests/protocolSource.test.ts.

/** The protocol major version: a breaking change. The handshake is answered only for this major. */
export const PROTOCOL_MAJOR: number = ${major};

/** The protocol minor version: bumped by every additive change. Informational; a host decides by capability. */
export const PROTOCOL_MINOR: number = ${minor};

export type CapabilityCondition = ${KNOWN_CONDITIONS.map(literal).join(' | ')};

/** Every capability a sidecar can advertise, in the order the handshake lists them. \`when\` marks the
 * ones that depend on the process or the build (see src/capabilities.ts). */
export const CAPABILITY_TABLE: ReadonlyArray<{
  readonly name: string;
  readonly sinceMinor: number;
  readonly baseline: boolean;
  readonly when: CapabilityCondition | undefined;
}> = [
${capabilities.map((c) => `  { name: ${literal(c.name)}, sinceMinor: ${c.sinceMinor}, baseline: ${c.baseline}, when: ${c.when === undefined ? 'undefined' : literal(c.when)} },`).join('\n')}
];

/** The permission modes the handshake lists. */
export const PERMISSION_MODES: ReadonlyArray<string> = ${literal(permissionModes)};
`,
  'utf8',
);
console.error(`generated ${out}: protocol ${major}.${minor}, ${capabilities.length} capabilities, ${permissionModes.length} permission modes`);
