// Generates src/generated/sdkVersions.ts: the three version strings this sidecar reports about
// itself, resolved ONCE at build time instead of at every process start.
//
// Why generated rather than read at runtime. The previous code did `require.resolve` on the agent
// SDK and then `readFileSync` of its package.json and manifest.json beside it, at module load. That
// works in a checkout and cannot work in a shipped artifact -- a single-file executable has no
// node_modules, so the bundle builds clean and dies on its first run with MODULE_NOT_FOUND, before
// binding anything. Measured 2026-09-18 while proving the SEA shape out. Generating puts the read
// where node_modules is guaranteed to exist (the build machine) and leaves the runtime with three
// string literals.
//
// The values are NOT allowed to drift from what is installed: tests/sdkVersions.test.ts re-reads all
// three from node_modules and fails if they disagree. `npm run build` regenerates before tsc, so the
// only way to ship a stale value is to bypass the build.

import { createRequire } from 'node:module';
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const workspaceRoot = join(here, '..');
const require = createRequire(import.meta.url);

// The package's own `exports` map does not expose a `./package.json` subpath, so requiring that
// specifier is refused outright (ERR_PACKAGE_PATH_NOT_EXPORTED). Resolve the real entry file first
// and read its siblings with plain fs -- a filesystem read, not a module resolution.
const sdkDir = dirname(require.resolve('@anthropic-ai/claude-agent-sdk'));
const readJson = (path) => JSON.parse(readFileSync(path, 'utf8'));

const claudeAgentSdkVersion = readJson(join(sdkDir, 'package.json')).version;
// The SDK's own declaration of the CLI it ships -- what an `executable: 'sdk_bundled'` session runs,
// a different program at a different version from the `claude` installed on the machine. Read from
// the manifest rather than by spawning it: no subprocess, and no reimplementation of the SDK's
// platform-specific resolution of its own optional native dependency.
const sdkDeclaredClaudeCodeVersion = readJson(join(sdkDir, 'manifest.json')).version;
const sidecarVersion = readJson(join(workspaceRoot, 'package.json')).version;

for (const [name, value] of Object.entries({ claudeAgentSdkVersion, sdkDeclaredClaudeCodeVersion, sidecarVersion })) {
  if (typeof value !== 'string' || value.trim() === '') {
    throw new Error(`generateSdkVersions: ${name} resolved to ${JSON.stringify(value)} -- refusing to generate a file that would report a missing version as if it were one`);
  }
}

const out = join(workspaceRoot, 'src', 'generated', 'sdkVersions.ts');
mkdirSync(dirname(out), { recursive: true });
writeFileSync(
  out,
  `// GENERATED by scripts/generateSdkVersions.mjs -- do not edit, and do not commit (src/generated/ is ignored).
// Regenerated by \`npm run generate\`, which \`npm run build\` runs first.
// Drift from what is installed is caught by tests/sdkVersions.test.ts.

/** The \`@anthropic-ai/claude-agent-sdk\` version this process was built against. */
export const CLAUDE_AGENT_SDK_VERSION = ${JSON.stringify(claudeAgentSdkVersion)};

/** The CLI version that SDK declares it ships -- what an \`executable: 'sdk_bundled'\` session runs. */
export const SDK_DECLARED_CLAUDE_CODE_VERSION = ${JSON.stringify(sdkDeclaredClaudeCodeVersion)};

/** This sidecar's own version, from its package.json. Reported in the handshake, and the version a
 * packaged client range-checks against -- a shipped artifact has a version, not a git revision. */
export const SIDECAR_VERSION = ${JSON.stringify(sidecarVersion)};
`,
  'utf8',
);
console.error(`generated ${out}: sdk ${claudeAgentSdkVersion}, sdk-declared cli ${sdkDeclaredClaudeCodeVersion}, sidecar ${sidecarVersion}`);
