//! Generated client types and message structs for verdandi.claude.runtime.v1 (design spec §1, §9).
//! No business logic lives here -- this crate's only job is compiling the canonical proto into Rust
//! types a future client can depend on.

pub mod v1 {
    tonic::include_proto!("verdandi.claude.runtime.v1");
}

// The protocol numbers, capability strings and permission-mode strings, generated by build.rs from
// capabilities.json (the one source, shared with the TypeScript sidecar). Additive to the crate's API:
// `PROTOCOL_MAJOR`, `PROTOCOL_MINOR`, `CAP_*`, `PERMISSION_MODE_*`, and the lists built from them.
// COMPATIBILITY.md says what each means and how a host should use it.
include!(concat!(env!("OUT_DIR"), "/protocol_constants.rs"));
