use std::{collections::HashSet, env, fmt::Write as _, fs, path::PathBuf};

use serde_json::Value;

/// `capabilities.json` is the one source for the protocol numbers, the capability strings and the
/// permission-mode strings (see COMPATIBILITY.md). This turns it into `$OUT_DIR/protocol_constants.rs`,
/// which `src/lib.rs` includes at the crate root: `PROTOCOL_MAJOR`, `PROTOCOL_MINOR`, one `CAP_*` per
/// capability, one `PERMISSION_MODE_*` per mode, and the lists built from those constants.
///
/// It refuses a malformed file instead of generating something plausible: a duplicate name, a name
/// that is not a valid constant, an `executable_*` capability that is not last (the wire order is
/// part of the contract), a capability introduced by a minor the ledger does not have.
fn generate_protocol_constants() -> Result<(), Box<dyn std::error::Error>> {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR")?);
    let source = manifest_dir.join("capabilities.json");
    println!("cargo:rerun-if-changed={}", source.display());
    let text = fs::read_to_string(&source).map_err(|e| format!("cannot read {}: {e}", source.display()))?;
    let doc: Value = serde_json::from_str(&text).map_err(|e| format!("{} is not valid JSON: {e}", source.display()))?;

    let number = |value: &Value, what: &str| -> Result<u64, String> {
        value.as_u64().ok_or_else(|| format!("capabilities.json: {what} must be a non-negative integer"))
    };
    let major = number(&doc["protocol"]["major"], "protocol.major")?;
    let minor = number(&doc["protocol"]["minor"], "protocol.minor")?;
    let ledger: Vec<u64> = doc["minors"]
        .as_array()
        .ok_or("capabilities.json: minors must be an array")?
        .iter()
        .map(|entry| number(&entry["minor"], "minors[].minor"))
        .collect::<Result<_, _>>()?;
    if ledger != (0..=minor).collect::<Vec<u64>>() {
        return Err(format!("capabilities.json: minors must list 0..={minor} in order, got {ledger:?}").into());
    }

    let is_name = |name: &str| {
        let mut chars = name.chars();
        chars.next().is_some_and(|c| c.is_ascii_lowercase())
            && name.chars().all(|c| c.is_ascii_lowercase() || c.is_ascii_digit() || c == '_')
    };
    let mut seen = HashSet::new();
    let mut all = Vec::new(); // (name, since_minor, baseline)
    for entry in doc["capabilities"].as_array().ok_or("capabilities.json: capabilities must be an array")? {
        let name = entry["name"].as_str().ok_or("capabilities.json: a capability has no name")?;
        if !is_name(name) || !seen.insert(name.to_owned()) {
            return Err(format!("capabilities.json: capability {name:?} is not a unique lower_snake_case name").into());
        }
        let since = number(&entry["since_minor"], &format!("{name}.since_minor"))?;
        if since > minor {
            return Err(format!("capabilities.json: {name} is since minor {since}, past the current {minor}").into());
        }
        let baseline = entry.get("baseline").and_then(Value::as_bool).unwrap_or(false);
        if baseline && since != 0 {
            return Err(format!("capabilities.json: {name} is baseline but since minor {since}; the baseline is what major {major} itself guarantees").into());
        }
        all.push((name.to_owned(), since, baseline));
    }
    if let Some(first_executable) = all.iter().position(|(name, _, _)| name.starts_with("executable_")) {
        if !all[first_executable..].iter().all(|(name, _, _)| name.starts_with("executable_")) {
            return Err("capabilities.json: the executable_* capabilities must stay last".into());
        }
    }
    let modes: Vec<String> = doc["permission_modes"]
        .as_array()
        .ok_or("capabilities.json: permission_modes must be an array")?
        .iter()
        .map(|mode| mode.as_str().filter(|m| is_name(m)).map(str::to_owned).ok_or("capabilities.json: a permission mode is not a lower_snake_case name"))
        .collect::<Result<_, _>>()?;

    let mut out = String::new();
    writeln!(out, "// GENERATED by build.rs from capabilities.json -- do not edit.")?;
    writeln!(out, "/// The protocol major version: a breaking change. A sidecar answers a handshake only for its own major.")?;
    writeln!(out, "pub const PROTOCOL_MAJOR: u32 = {major};")?;
    writeln!(out, "/// The protocol minor version: bumped by every additive change. Informational; a host decides by capability.")?;
    writeln!(out, "pub const PROTOCOL_MINOR: u32 = {minor};")?;
    for (name, since, _) in &all {
        writeln!(out, "/// Capability `{name}` (introduced by minor {since}).")?;
        writeln!(out, "pub const CAP_{}: &str = {name:?};", name.to_uppercase())?;
    }
    writeln!(out, "/// Every capability a sidecar can advertise, in the order the handshake lists them. Some are conditional on the build or the process (see COMPATIBILITY.md).")?;
    writeln!(out, "pub const CAPABILITIES: &[&str] = &[")?;
    for (name, _, _) in &all {
        writeln!(out, "    CAP_{},", name.to_uppercase())?;
    }
    writeln!(out, "];")?;
    writeln!(out, "/// The major-{major} baseline: what every sidecar that answers protocol major {major} guarantees, with no further check.")?;
    writeln!(out, "pub const BASELINE_CAPABILITIES: &[&str] = &[")?;
    for (name, _, _) in all.iter().filter(|(_, _, baseline)| *baseline) {
        writeln!(out, "    CAP_{},", name.to_uppercase())?;
    }
    writeln!(out, "];")?;
    writeln!(out, "/// Each capability with the protocol minor that introduced it.")?;
    writeln!(out, "pub const CAPABILITY_SINCE_MINOR: &[(&str, u32)] = &[")?;
    for (name, since, _) in &all {
        writeln!(out, "    (CAP_{}, {since}),", name.to_uppercase())?;
    }
    writeln!(out, "];")?;
    for mode in &modes {
        writeln!(out, "/// Permission mode `{mode}`.")?;
        writeln!(out, "pub const PERMISSION_MODE_{}: &str = {mode:?};", mode.to_uppercase())?;
    }
    writeln!(out, "/// The permission modes a handshake lists.")?;
    writeln!(out, "pub const PERMISSION_MODES: &[&str] = &[")?;
    for mode in &modes {
        writeln!(out, "    PERMISSION_MODE_{},", mode.to_uppercase())?;
    }
    writeln!(out, "];")?;
    fs::write(PathBuf::from(env::var("OUT_DIR")?).join("protocol_constants.rs"), out)?;
    Ok(())
}

fn main() -> Result<(), Box<dyn std::error::Error>> {
    generate_protocol_constants()?;
    // No Rust server this round -- verdandi's server is the Node sidecar; this crate is a future
    // Rust CLIENT's dependency only (design spec §1, §9). build_server(false) avoids generating and
    // compiling server-side trait scaffolding with zero consumers.
    //
    // NOTE: as of tonic 0.13/0.14, prost codegen (configure()/compile()) moved out of `tonic-build`
    // into `tonic-prost-build`, and `compile()` was renamed `compile_protos()` -- this plan's brief
    // was written against the pre-split tonic 0.12 API. This is the current-stable equivalent;
    // `tonic::include_proto!` in src/lib.rs is unaffected since it just includes a generated file by
    // package name, regardless of which build crate produced it.
    // The proto lives OUTSIDE this package (`../../proto`), and cargo's default rerun heuristic only
    // watches files inside the package directory -- so without these, editing the contract leaves
    // the previously generated code in place and the crate compiles, and passes tests, against a
    // contract that no longer exists. Reported by a sibling runtime track, which hit exactly this
    // in its own protocol crate: 4 tests green against a deleted shape.
    //
    // A fresh `rev`-pinned checkout (how neovibe consumes this crate) builds once and is unaffected;
    // the hole is for anyone editing the proto inside this repo, which is now everyone doing
    // protocol work.
    println!("cargo:rerun-if-changed=../../proto/verdandi/claude/runtime/v1/runtime.proto");
    println!("cargo:rerun-if-changed=../../proto");

    tonic_prost_build::configure()
        .build_server(false)
        .compile_protos(
            &["../../proto/verdandi/claude/runtime/v1/runtime.proto"],
            &["../../proto"],
        )?;
    Ok(())
}
